pipeline {
    agent any
    stages {
        stage('Running the Rover Application using JDK_10') {
            steps {
               sh script: '''
                chmod +x gradlew
                .gradlew build
                ''',
                label: "Building Project"
            }
        }
        stage('Running the Tests') {
            steps {
                sh script: '''
                    ./gradlew test
                ''',
                label: "Building Project"
            }
        }
    }
}