pipeline {
    agent {label "machine"}
    stages {
        stage('Running the Rover Application using JDK_10') {
            steps {
               bat label: '', script: '''
                set JAVA_HOME="C:\\Program Files\\Java\\jdk-10"
                echo $JAVA_HOME
                .\\gradlew.bat build
                cd ..
                @RD /S /Q Merchant-Galaxy-Problem
               '''
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}